[build]
  # This is the build command to compile your React application
  command = "npm run build"

  # This is the directory to publish after building
  publish = "build"

[build.environment]
  # Define your environment variables here
  GOOGLE_APPLICATION_CREDENTIALS = "./active-tangent-428009-a6-a349260cd362.json"
  SKIP_PREFLIGHT_CHECK = "true"
  HOST = "0.0.0.0"
  PORT = "3000"
